# Generated by Django 2.2.1 on 2019-10-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0002_auto_20190922_2038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'section_name')},
        ),
    ]
